config/routes.rb
Rails.application.routes.draw do
  
  root 'poses#index'

  get 'pages/oriane'
  get 'pages/practice'
  get 'pages/live_classes'
  get 'pages/retreats'
  

  resources :sequences
  resources :poses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pose.rb
class Pose < ApplicationRecord
end

app/models/sequence.rb
class Sequence < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def oriane
  end

  def practice
  end

  def live_classes
  end

  def retreats
  end
end

app/controllers/poses_controller.rb
class PosesController < ApplicationController
  before_action :set_pose, only: [:show, :edit, :update, :destroy]

  # GET /poses
  # GET /poses.json
  def index
    @poses = Pose.all
  end

  # GET /poses/1
  # GET /poses/1.json
  def show
  end

  # GET /poses/new
  def new
    @pose = Pose.new
  end

  # GET /poses/1/edit
  def edit
  end

  # POST /poses
  # POST /poses.json
  def create
    @pose = Pose.new(pose_params)

    respond_to do |format|
      if @pose.save
        format.html { redirect_to @pose, notice: 'Pose was successfully created.' }
        format.json { render :show, status: :created, location: @pose }
      else
        format.html { render :new }
        format.json { render json: @pose.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poses/1
  # PATCH/PUT /poses/1.json
  def update
    respond_to do |format|
      if @pose.update(pose_params)
        format.html { redirect_to @pose, notice: 'Pose was successfully updated.' }
        format.json { render :show, status: :ok, location: @pose }
      else
        format.html { render :edit }
        format.json { render json: @pose.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poses/1
  # DELETE /poses/1.json
  def destroy
    @pose.destroy
    respond_to do |format|
      format.html { redirect_to poses_url, notice: 'Pose was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pose
      @pose = Pose.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pose_params
      params.require(:pose).permit(:english_name, :sanskrit_name, :demo_icon_url, :demo_vid_url)
    end
end

app/controllers/sequences_controller.rb
class SequencesController < ApplicationController
  before_action :set_sequence, only: [:show, :edit, :update, :destroy]

  # GET /sequences
  # GET /sequences.json
  def index
    @sequences = Sequence.all
  end

  # GET /sequences/1
  # GET /sequences/1.json
  def show
  end

  # GET /sequences/new
  def new
    @sequence = Sequence.new
  end

  # GET /sequences/1/edit
  def edit
  end

  # POST /sequences
  # POST /sequences.json
  def create
    @sequence = Sequence.new(sequence_params)

    respond_to do |format|
      if @sequence.save
        format.html { redirect_to @sequence, notice: 'Sequence was successfully created.' }
        format.json { render :show, status: :created, location: @sequence }
      else
        format.html { render :new }
        format.json { render json: @sequence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sequences/1
  # PATCH/PUT /sequences/1.json
  def update
    respond_to do |format|
      if @sequence.update(sequence_params)
        format.html { redirect_to @sequence, notice: 'Sequence was successfully updated.' }
        format.json { render :show, status: :ok, location: @sequence }
      else
        format.html { render :edit }
        format.json { render json: @sequence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sequences/1
  # DELETE /sequences/1.json
  def destroy
    @sequence.destroy
    respond_to do |format|
      format.html { redirect_to sequences_url, notice: 'Sequence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sequence
      @sequence = Sequence.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sequence_params
      params.require(:sequence).permit(:name, :pose_1_id, :pose_2_id, :pose_3_id, :pose_4_id, :pose_5_id, :pose_6_id, :pose_7_id, :pose_8_id, :pose_9_id, :pose_10_id, :pose_11_id, :pose_12_id, :pose_13_id, :pose_14_id, :pose_15_id, :pose_16_id, :pose_17_id, :pose_18_id, :pose_19_id, :pose_20_id, :pose_21_id, :pose_22_id, :pose_23_id, :pose_24_id, :pose_25_id, :pose_26_id, :pose_27_id, :pose_28_id, :pose_29_id, :pose_30_id, :pose_31_id, :pose_32_id, :pose_33_id, :pose_34_id, :pose_35_id, :pose_36_id, :pose_37_id, :pose_38_id, :pose_39_id, :pose_40_id, :pose_41_id, :pose_42_id, :pose_43_id, :pose_44_id, :pose_45_id, :pose_46_id, :pose_47_id, :pose_48_id, :pose_49_id, :pose_50_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/poses_helper.rb
module PosesHelper
end

app/helpers/sequences_helper.rb
module SequencesHelper
end

app/views/layouts/_foot.html.erb
<nav class="navbar fixed-bottom navbar-dark bg-dark">
	<ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <table>
          <tr>
            <td><%= link_to "poses", poses_path, class: "nav-link" %></td>
            <td><%= link_to "sequences", sequences_path, class: "nav-link" %></td>
            <td><%= link_to " | ", "#", class: "nav-link" %></td>
            <td><%= link_to "Oriane", pages_oriane_path, class: "nav-link" %></td>
            <td><%= link_to "Practice", pages_practice_path, class: "nav-link" %></td>
            <td><%= link_to "Live clases", pages_live_classes_path, class: "nav-link" %></td>
            <td><%= link_to "Retreats", pages_retreats_path, class: "nav-link" %></td>
          </tr>
        </table>
      </li>
  </ul>

  <ul class="navbar-nav">
  	<li class="nav-item">
		<copyright>copyright © Oriane 2020</copyright>
    </li>
  </ul>
</nav>

app/views/layouts/_nav.html.erb
  <footer id="sticky-footer" class="py-4 bg-dark text-white-50 navbar-fixed-bottom">
    <div class="container-fluid">
      <small><%= link_to "POSES", poses_path %></small>
      <small><%= link_to "SEQUENCES", sequences_path %></small>
      <span class="right"><small>Copyright &copy; Oriane 2020</small></span>
    </div>
  </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instructions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= render 'layouts/foot' %>
  </body>
</html>

app/views/pages/live_classes.html.erb
<h1>Pages#live_classes</h1>
<p>Find me in app/views/pages/live_classes.html.erb</p>

app/views/pages/oriane.html.erb
<h1>Pages#oriane</h1>
<p>Find me in app/views/pages/oriane.html.erb</p>

app/views/poses/edit.html.erb
<h1>Editing Pose</h1>

<%= render 'form', pose: @pose %>

<%= link_to 'Show', @pose %> |
<%= link_to 'Back', poses_path %>

app/views/poses/new.html.erb
<h1>New Pose</h1>

<%= render 'form', pose: @pose %>

<%= link_to 'Back', poses_path %>

app/views/poses/show.html.erb
<p id="notice"><%= notice %></p>

<table>
	<tr>
		<td>
			<p>
				<%= image_tag("#{@pose.demo_icon_url}", size: "222") %>
			</p>
		</td>
		<td>
			<p>
			  <strong>English name:</strong>
			  <%= @pose.english_name %>
			</p>

			<p>
			  <strong>Sanskrit name:</strong>
			  <%= @pose.sanskrit_name %>
			</p>

			<p>
			  <strong>Demo icon url:</strong>
			  <%= @pose.demo_icon_url %>
			</p>
			<p>
			  <strong>Demo video url:</strong>
			  <%= @pose.demo_vid_url %>
			</p>
		</td>
	</tr>
</table>

<%= link_to 'Edit', edit_pose_path(@pose) %> |
<%= link_to 'Destroy', @pose, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', poses_path %>


<div class="vid-grid-container">
	<div class="vid-grid-item">
		<iframe width="700" height="394" src="http://www.youtube.com/embed/<%= @pose.demo_vid_url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
</div>

app/views/sequences/edit.html.erb
<div class="page-container">
	<h1>Editing Sequence</h1>

	<%= render 'form', sequence: @sequence %>

	<%= link_to 'Show', @sequence %> |
	<%= link_to 'Back', sequences_path %>
</div>

app/views/sequences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sequences</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pose 1</th>
      <th>Pose 2</th>
      <th>Pose 3</th>
      <th>Pose 4</th>
      <th>Pose 5</th>
      <th>Pose 6</th>
      <th>Pose 7</th>
      <th>Pose 8</th>
      <th>Pose 9</th>
      <th>Pose 10</th>
      <th>Pose 11</th>
      <th>Pose 12</th>
      <th>Pose 13</th>
      <th>Pose 14</th>
      <th>Pose 15</th>
      <th>Pose 16</th>
      <th>Pose 17</th>
      <th>Pose 18</th>
      <th>Pose 19</th>
      <th>Pose 20</th>
      <th>Pose 21</th>
      <th>Pose 22</th>
      <th>Pose 23</th>
      <th>Pose 24</th>
      <th>Pose 25</th>
      <th>Pose 26</th>
      <th>Pose 27</th>
      <th>Pose 28</th>
      <th>Pose 29</th>
      <th>Pose 30</th>
      <th>Pose 31</th>
      <th>Pose 32</th>
      <th>Pose 33</th>
      <th>Pose 34</th>
      <th>Pose 35</th>
      <th>Pose 36</th>
      <th>Pose 37</th>
      <th>Pose 38</th>
      <th>Pose 39</th>
      <th>Pose 40</th>
      <th>Pose 41</th>
      <th>Pose 42</th>
      <th>Pose 43</th>
      <th>Pose 44</th>
      <th>Pose 45</th>
      <th>Pose 46</th>
      <th>Pose 47</th>
      <th>Pose 48</th>
      <th>Pose 49</th>
      <th>Pose 50</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sequences.each do |sequence| %>
      <tr>
        <td><%= link_to sequence.name, sequence %></td>
        <td><%= sequence.pose_1_id %></td>
        <td><%= sequence.pose_2_id %></td>
        <td><%= sequence.pose_3_id %></td>
        <td><%= sequence.pose_4_id %></td>
        <td><%= sequence.pose_5_id %></td>
        <td><%= sequence.pose_6_id %></td>
        <td><%= sequence.pose_7_id %></td>
        <td><%= sequence.pose_8_id %></td>
        <td><%= sequence.pose_9_id %></td>
        <td><%= sequence.pose_10_id %></td>
        <td><%= sequence.pose_11_id %></td>
        <td><%= sequence.pose_12_id %></td>
        <td><%= sequence.pose_13_id %></td>
        <td><%= sequence.pose_14_id %></td>
        <td><%= sequence.pose_15_id %></td>
        <td><%= sequence.pose_16_id %></td>
        <td><%= sequence.pose_17_id %></td>
        <td><%= sequence.pose_18_id %></td>
        <td><%= sequence.pose_19_id %></td>
        <td><%= sequence.pose_20_id %></td>
        <td><%= sequence.pose_21_id %></td>
        <td><%= sequence.pose_22_id %></td>
        <td><%= sequence.pose_23_id %></td>
        <td><%= sequence.pose_24_id %></td>
        <td><%= sequence.pose_25_id %></td>
        <td><%= sequence.pose_26_id %></td>
        <td><%= sequence.pose_27_id %></td>
        <td><%= sequence.pose_28_id %></td>
        <td><%= sequence.pose_29_id %></td>
        <td><%= sequence.pose_30_id %></td>
        <td><%= sequence.pose_31_id %></td>
        <td><%= sequence.pose_32_id %></td>
        <td><%= sequence.pose_33_id %></td>
        <td><%= sequence.pose_34_id %></td>
        <td><%= sequence.pose_35_id %></td>
        <td><%= sequence.pose_36_id %></td>
        <td><%= sequence.pose_37_id %></td>
        <td><%= sequence.pose_38_id %></td>
        <td><%= sequence.pose_39_id %></td>
        <td><%= sequence.pose_40_id %></td>
        <td><%= sequence.pose_41_id %></td>
        <td><%= sequence.pose_42_id %></td>
        <td><%= sequence.pose_43_id %></td>
        <td><%= sequence.pose_44_id %></td>
        <td><%= sequence.pose_45_id %></td>
        <td><%= sequence.pose_46_id %></td>
        <td><%= sequence.pose_47_id %></td>
        <td><%= sequence.pose_48_id %></td>
        <td><%= sequence.pose_49_id %></td>
        <td><%= sequence.pose_50_id %></td>
        <td><%= link_to 'Show', sequence %></td>
        <td><%= link_to 'Edit', edit_sequence_path(sequence) %></td>
        <td><%= link_to 'Destroy', sequence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sequence', new_sequence_path %>

app/views/sequences/new.html.erb
<div class="page-container">
	<h1>New Sequence</h1>

	<%= render 'form', sequence: @sequence %>

	<%= link_to 'Back', sequences_path %>
</div>

app/views/sequences/show.html.erb
<p id="notice"><%= notice %></p>





<h1 class="section-head">
  <%= @sequence.name %>
</h1>

<p align="center">
  <%= link_to 'Edit', edit_sequence_path(@sequence) %> |
  <%= link_to 'Destroy', @sequence, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <%= link_to 'Back', sequences_path %>
</p>

<table class="sequence-table">

  <tr>
    <td>
    
    </td>  
  </tr>

  <tr>
    
    <% @sequence.attributes.each{|obj| %>
      <% if obj[0].include?("pose_") and obj[1] != nil %>
        
        <td align="center">
          <% @pose_id = obj[1] %>

          <%= link_to (Pose.where(id: @pose_id)[0]) do %>
            <%= image_tag Pose.where(id: @pose_id)[0].demo_icon_url, size: 88, class: "demo-icon-img" %>
          <% end -%>
          

          <div class="img-labels">
          <%= Pose.where(id: @pose_id)[0].english_name %><br>
          <%= Pose.where(id: @pose_id)[0].sanskrit_name %>
          </div>
        </td>

      <% end %>
    <% } %>  

  </tr>

</table>

<br><br><br>
<hr>
<br><br><br>

<h1 class="section-head">
  <%= @sequence.name %>
</h1>

<p align="center">
  <%= link_to 'Edit', edit_sequence_path(@sequence) %> |
  <%= link_to 'Destroy', @sequence, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <%= link_to 'Back', sequences_path %>
</p>

<p>
  <strong>Pose 1:</strong>

<% if @sequence.pose_1_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_1_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 2:</strong>

<% if @sequence.pose_2_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_2_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 3:</strong>

<% if @sequence.pose_3_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_3_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 4:</strong>

<% if @sequence.pose_4_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_4_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 5:</strong>

<% if @sequence.pose_5_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_5_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 6:</strong>

<% if @sequence.pose_6_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_6_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 7:</strong>

<% if @sequence.pose_7_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_7_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 8:</strong>

<% if @sequence.pose_8_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_8_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 9:</strong>

<% if @sequence.pose_9_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_9_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 10:</strong>

<% if @sequence.pose_10_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_10_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 11:</strong>

<% if @sequence.pose_11_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_11_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 12:</strong>

<% if @sequence.pose_12_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_12_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 13:</strong>

<% if @sequence.pose_13_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_13_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 14:</strong>

<% if @sequence.pose_14_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_14_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 15:</strong>

<% if @sequence.pose_15_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_15_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 16:</strong>

<% if @sequence.pose_16_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_16_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 17:</strong>

<% if @sequence.pose_17_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_17_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 18:</strong>

<% if @sequence.pose_18_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_18_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 19:</strong>

<% if @sequence.pose_19_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_19_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 20:</strong>

<% if @sequence.pose_20_id == nil %>
  <%= "~ nil ~"%>
<% else %>
  <% @pose = Pose.where(id: @sequence.pose_20_id)[0] %>
  <table>
    <tr>
      <td><%= image_tag(@pose.demo_icon_url.to_s, size: "44") %></td>
      <td><%= @pose.english_name %></td>
    </tr>
  </table>
  
<% end -%>

</p>

<p>
  <strong>Pose 21:</strong>
  <%= @sequence.pose_21_id %>
</p>

<p>
  <strong>Pose 22:</strong>
  <%= @sequence.pose_22_id %>
</p>

<p>
  <strong>Pose 23:</strong>
  <%= @sequence.pose_23_id %>
</p>

<p>
  <strong>Pose 24:</strong>
  <%= @sequence.pose_24_id %>
</p>

<p>
  <strong>Pose 25:</strong>
  <%= @sequence.pose_25_id %>
</p>

<p>
  <strong>Pose 26:</strong>
  <%= @sequence.pose_26_id %>
</p>

<p>
  <strong>Pose 27:</strong>
  <%= @sequence.pose_27_id %>
</p>

<p>
  <strong>Pose 28:</strong>
  <%= @sequence.pose_28_id %>
</p>

<p>
  <strong>Pose 29:</strong>
  <%= @sequence.pose_29_id %>
</p>

<p>
  <strong>Pose 30:</strong>
  <%= @sequence.pose_30_id %>
</p>

<p>
  <strong>Pose 31:</strong>
  <%= @sequence.pose_31_id %>
</p>

<p>
  <strong>Pose 32:</strong>
  <%= @sequence.pose_32_id %>
</p>

<p>
  <strong>Pose 33:</strong>
  <%= @sequence.pose_33_id %>
</p>

<p>
  <strong>Pose 34:</strong>
  <%= @sequence.pose_34_id %>
</p>

<p>
  <strong>Pose 35:</strong>
  <%= @sequence.pose_35_id %>
</p>

<p>
  <strong>Pose 36:</strong>
  <%= @sequence.pose_36_id %>
</p>

<p>
  <strong>Pose 37:</strong>
  <%= @sequence.pose_37_id %>
</p>

<p>
  <strong>Pose 38:</strong>
  <%= @sequence.pose_38_id %>
</p>

<p>
  <strong>Pose 39:</strong>
  <%= @sequence.pose_39_id %>
</p>

<p>
  <strong>Pose 40:</strong>
  <%= @sequence.pose_40_id %>
</p>

<p>
  <strong>Pose 41:</strong>
  <%= @sequence.pose_41_id %>
</p>

<p>
  <strong>Pose 42:</strong>
  <%= @sequence.pose_42_id %>
</p>

<p>
  <strong>Pose 43:</strong>
  <%= @sequence.pose_43_id %>
</p>

<p>
  <strong>Pose 44:</strong>
  <%= @sequence.pose_44_id %>
</p>

<p>
  <strong>Pose 45:</strong>
  <%= @sequence.pose_45_id %>
</p>

<p>
  <strong>Pose 46:</strong>
  <%= @sequence.pose_46_id %>
</p>

<p>
  <strong>Pose 47:</strong>
  <%= @sequence.pose_47_id %>
</p>

<p>
  <strong>Pose 48:</strong>
  <%= @sequence.pose_48_id %>
</p>

<p>
  <strong>Pose 49:</strong>
  <%= @sequence.pose_49_id %>
</p>

<p>
  <strong>Pose 50:</strong>
  <%= @sequence.pose_50_id %>
</p>